apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim
spec:
  storageClassName: ""
  selector:
    matchLabels:
      type: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
