apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-task1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-task1
  template:
    metadata:
      labels:
        app: nginx-task1
    spec:
      containers:
        - name: web-task1
          image: nginx:latest
          ports:
          - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always
